language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

script:

    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # add MATLAB to the path
    - if [ "$ARCH" == "Linux" ]; then
          export PATH="$PATH:$ARTENOLIS_SOFT_PATH/MATLAB/$MATLAB_VER/bin";
      fi

    # change to the current directory
    - cd $CURRENT_DIR

    # rename the cloned folder
    - cd .. && cp -r $NODE_LABELS COBRA && cd COBRA

    # change the test dependencies on Linux and macOS (ARTENOLIS)
    - if [ "$ARCH" == "Linux" ] || [ "$ARCH" == "macOS" ]; then
          CURRENT_DIR=`pwd`;
          cd ~/tmp/cobratoolbox-cobrajl;
          git pull origin master;
          cd $CURRENT_DIR;
          perl -i -pe's/test = \["GLPKMathProgInterface", "GLPK", "Test"\]/test = \["GLPKMathProgInterface", "GLPK", "Test", "MAT", "MATLAB", "Gurobi", "CPLEX"\]/g' Project.toml;
      fi

    # launch the tests
    - bash .artenolis/runtests.sh

after_success:

    # submit coverage report
    - if [[ "$ARCH" == "Linux" && "$JULIA_VER" == "v1.2.0" ]]; then
        $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --color=yes -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
      fi

    # set environment variables for documentation deployment
    - if [[ "$ARCH" == "Linux" && "$JENKINS_PULL_REQUEST" != "True" ]]; then
        export TRAVIS_BRANCH=$GIT_BRANCH;
        export TRAVIS_PULL_REQUEST=false;
        var=$GIT_URL; export TRAVIS_REPO_SLUG=${var:7:${#var}};
        export TRAVIS_OS_NAME=$label;
        export TRAVIS_JULIA_VERSION=$JULIA_VER;
        $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()';
        $ARTENOLIS_SOFT_PATH/julia/$JULIA_VER/bin/julia --project=docs/ docs/make.jl;
      fi

after_script:
    # clean up the build directory
    - cd .. && rm -rf COBRA
