language: julia

os:
    - linux

julia:
    - 1.0
    - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
    email: false

sudo: required

addons:
    apt_packages:
        - gfortran
        - liblapack-dev
        - libgmp-dev
        - libglpk-dev

